/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RoadmapImport } from './routes/roadmap'
import { Route as OverviewImport } from './routes/overview'
import { Route as IndexImport } from './routes/index'
import { Route as SprintIdDailyImport } from './routes/$sprintId/daily'

// Create/Update Routes

const RoadmapRoute = RoadmapImport.update({
  path: '/roadmap',
  getParentRoute: () => rootRoute,
} as any)

const OverviewRoute = OverviewImport.update({
  path: '/overview',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SprintIdDailyRoute = SprintIdDailyImport.update({
  path: '/$sprintId/daily',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewImport
      parentRoute: typeof rootRoute
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapImport
      parentRoute: typeof rootRoute
    }
    '/$sprintId/daily': {
      id: '/$sprintId/daily'
      path: '/$sprintId/daily'
      fullPath: '/$sprintId/daily'
      preLoaderRoute: typeof SprintIdDailyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  OverviewRoute,
  RoadmapRoute,
  SprintIdDailyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/overview",
        "/roadmap",
        "/$sprintId/daily"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/overview": {
      "filePath": "overview.tsx"
    },
    "/roadmap": {
      "filePath": "roadmap.tsx"
    },
    "/$sprintId/daily": {
      "filePath": "$sprintId/daily.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
